server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: alan-user-center

  # MySQL 数据库 config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alan-usercenter
    username: root
    password: 123456
  # session超时时间,默认一天
  session:
    timeout: 86400


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名规则
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值